language: java
sudo: required
jdk:
- oraclejdk8
services:
    - docker
    
before_install:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
    - export VERSION=version-0.37.0
    - bash prep_and_build.sh "$VERSION"
